src/Rubius/AdminBundle/Entity/Content.php
<?php

namespace Rubius\AdminBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Content
 *
 * @ORM\Table()
 * @ORM\Entity(repositoryClass="Rubius\AdminBundle\Entity\Repository\ContentRepository")
 */
class Content
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="title", type="string", length=255)
     */
    private $title;

    /**
     * @var string
     *
     * @ORM\Column(name="alias", type="string", length=255)
     */
    private $alias;

    /**
     * @var string
     *
     * @ORM\Column(name="intro", type="text", nullable=true)
     */
    private $intro;

    /**
     * @var string
     *
     * @ORM\Column(name="body", type="string", length=255, nullable=true)
     */
    private $body;

    /**
     * @var boolean
     *
     * @ORM\Column(name="active", type="boolean", options={"default"=0})
     */
    private $active;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="publishedDate", type="datetime", nullable=true)
     */
    private $publishedDate;

    /**
     * @var string
     *
     * @ORM\Column(name="smallImage", type="string", length=255, nullable=true)
     */
    private $smallImage;

    /**
     * @Assert\File(
     *     maxSize = "5M",
     *     mimeTypes = {"image/jpeg", "image/gif", "image/png", "image/tiff"},
     *     maxSizeMessage = "The maxmimum allowed file size is 5MB.",
     *     mimeTypesMessage = "Only the filetypes image are allowed."
     * )
     */
    protected $smallImageObject;

    /**
     * @var string
     *
     * @ORM\Column(name="mediumImage", type="string", length=255, nullable=true)
     */
    private $mediumImage;

    /**
     * @Assert\File(
     *     maxSize = "5M",
     *     mimeTypes = {"image/jpeg", "image/gif", "image/png", "image/tiff"},
     *     maxSizeMessage = "The maxmimum allowed file size is 5MB.",
     *     mimeTypesMessage = "Only the filetypes image are allowed."
     * )
     */
    protected $mediumImageObject;

    /**
     * @var string
     *
     * @ORM\Column(name="bigImage", type="string", length=255, nullable=true)
     */
    private $bigImage;

    /**
     * @Assert\File(
     *     maxSize = "5M",
     *     mimeTypes = {"image/jpeg", "image/gif", "image/png", "image/tiff"},
     *     maxSizeMessage = "The maxmimum allowed file size is 5MB.",
     *     mimeTypesMessage = "Only the filetypes image are allowed."
     * )
     */
    protected $bigImageObject;

    /**
     * @var string
     *
     * @ORM\Column(name="metaTags", type="string", length=255, nullable=true)
     */
    private $metaTags;

    /**
     * @var string
     *
     * @ORM\Column(name="metaDescription", type="string", length=255, nullable=true)
     */
    private $metaDescription;

    /**
     * @var string
     *
     * @ORM\Column(name="forwardUrl", type="string", length=255, nullable=true)
     */
    private $forwardUrl;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="createdAt", type="datetime")
     */
    private $createdAt;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="updatedAt", type="datetime")
     */
    private $updatedAt;

    /**
     * @var string
     *
     * @ORM\ManyToOne(targetEntity="Rubius\AdminBundle\Entity\User", inversedBy="createdContents")
     * @ORM\JoinColumn(name="createdBy", referencedColumnName="id")
     */
    private $createdBy;

    /**
     * @var string
     *
     * @ORM\ManyToOne(targetEntity="Rubius\AdminBundle\Entity\User", inversedBy="updatedContents")
     * @ORM\JoinColumn(name="updatedBy", referencedColumnName="id")
     */
    private $updatedBy;

    /**
     * @var ContentType
     * @ORM\ManyToOne(targetEntity="Rubius\AdminBundle\Entity\ContentType", inversedBy="contents")
     * @ORM\JoinColumn(name="content_type_id", referencedColumnName="id")
     */
    private $contentType;

    function __construct()
    {
        $this->setCreatedAt(new \DateTime('now'));
        $this->setUpdatedAt(new \DateTime('now'));
    }


    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set title
     *
     * @param string $title
     *
     * @return Content
     */
    public function setTitle($title)
    {
        $this->title = $title;

        return $this;
    }

    /**
     * Get title
     *
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Set alias
     *
     * @param string $alias
     *
     * @return Content
     */
    public function setAlias($alias)
    {
        $this->alias = $alias;

        return $this;
    }

    /**
     * Get alias
     *
     * @return string
     */
    public function getAlias()
    {
        return $this->alias;
    }

    /**
     * Set intro
     *
     * @param string $intro
     *
     * @return Content
     */
    public function setIntro($intro)
    {
        $this->intro = $intro;

        return $this;
    }

    /**
     * Get intro
     *
     * @return string
     */
    public function getIntro()
    {
        return $this->intro;
    }

    /**
     * Set body
     *
     * @param string $body
     *
     * @return Content
     */
    public function setBody($body)
    {
        $this->body = $body;

        return $this;
    }

    /**
     * Get body
     *
     * @return string
     */
    public function getBody()
    {
        return $this->body;
    }

    /**
     * Set active
     *
     * @param boolean $active
     *
     * @return Content
     */
    public function setActive($active)
    {
        $this->active = $active;

        return $this;
    }

    /**
     * Get active
     *
     * @return boolean
     */
    public function getActive()
    {
        return $this->active;
    }

    /**
     * Set publishedDate
     *
     * @param \DateTime $publishedDate
     *
     * @return Content
     */
    public function setPublishedDate($publishedDate)
    {
        $this->publishedDate = $publishedDate ;//\Datetime::createFromFormat('d/m/Y', $publishedDate);

        return $this;
    }

    /**
     * Get publishedDate
     *
     * @return \DateTime
     */
    public function getPublishedDate()
    {
        return $this->publishedDate;
    }

    /**
     * Set smallImage
     *
     * @param string $smallImage
     *
     * @return Content
     */
    public function setSmallImage($smallImage)
    {
        $this->smallImage = $smallImage;

        return $this;
    }

    /**
     * Get smallImage URL
     *
     * @return string
     */
    public function getSmallImageUrl()
    {
        return sprintf("%s/%s",$this->getUploadDir(), $this->getSmallImage());
    }

    /**
     * Get smallImage
     *
     * @return string
     */
    public function getSmallImage()
    {
        return $this->smallImage;
    }

    /**
     * Set mediumImage
     *
     * @param string $mediumImage
     *
     * @return Content
     */
    public function setMediumImage($mediumImage)
    {
        $this->mediumImage = $mediumImage;

        return $this;
    }

    /**
     * Get mediumImage
     *
     * @return string
     */
    public function getMediumImage()
    {
        return $this->mediumImage;
    }

    /**
     * Get smallImage URL
     *
     * @return string
     */
    public function getMediumImageUrl()
    {
        return sprintf("%s/%s",$this->getUploadDir(), $this->getSmallImage());
    }

    /**
     * Set bigImage
     *
     * @param string $bigImage
     *
     * @return Content
     */
    public function setBigImage($bigImage)
    {
        $this->bigImage = $bigImage;

        return $this;
    }

    /**
     * Get smallImage URL
     *
     * @return string
     */
    public function getBigImageUrl()
    {
        return sprintf("%s/%s",$this->getUploadDir(), $this->getSmallImage());
    }

    /**
     * Get bigImage
     *
     * @return string
     */
    public function getBigImage()
    {
        return $this->bigImage;
    }

    /**
     * Set metaTags
     *
     * @param string $metaTags
     *
     * @return Content
     */
    public function setMetaTags($metaTags)
    {
        $this->metaTags = $metaTags;

        return $this;
    }

    /**
     * Get metaTags
     *
     * @return string
     */
    public function getMetaTags()
    {
        return $this->metaTags;
    }

    /**
     * Set metaDescription
     *
     * @param string $metaDescription
     *
     * @return Content
     */
    public function setMetaDescription($metaDescription)
    {
        $this->metaDescription = $metaDescription;

        return $this;
    }

    /**
     * Get metaDescription
     *
     * @return string
     */
    public function getMetaDescription()
    {
        return $this->metaDescription;
    }

    /**
     * Set forwardUrl
     *
     * @param string $forwardUrl
     *
     * @return Content
     */
    public function setForwardUrl($forwardUrl)
    {
        $this->forwardUrl = $forwardUrl;

        return $this;
    }

    /**
     * Get forwardUrl
     *
     * @return string
     */
    public function getForwardUrl()
    {
        return $this->forwardUrl;
    }

    /**
     * Set createdAt
     *
     * @param \DateTime $createdAt
     *
     * @return Content
     */
    public function setCreatedAt($createdAt)
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * Get createdAt
     *
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * Set updatedAt
     *
     * @param \DateTime $updatedAt
     *
     * @return Content
     */
    public function setUpdatedAt($updatedAt)
    {
        $this->updatedAt = $updatedAt;

src/Rubius/AdminBundle/Controller/CMS/ContentController.php
<?php

/**
 * @Author: Rúdi Rocha <rudi.rocha@gmail.com>
 */
namespace Rubius\AdminBundle\Controller\CMS;

use Rubius\AdminBundle\Entity\Content;
use Rubius\DataTablesBundle\Library\DataTablesInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Class ContentController
 * @package Rubius\AdminBundle\Controller\CMS
 * @Security("has_role('ROLE_ADMIN')")
 */
class ContentController extends \Rubius\AdminBundle\Controller\DefaultController
{

    /**
     * @Route(path="/", name="rubius_content_index")
     */
    public function indexAction()
    {
        /** @var DataTablesInterface $table */
        $table = $this->get('datatable.factory')->getTable('contents');

        return $this->render(
            'RubiusAdminBundle:CMS/content:index.html.twig',
            [
                'table' => $table->getDataTableObject($this->generateUrl('rubius_content_datatable'))
            ]
        );

    }

    /**
     * @Route(path="/getContentTypesData", name="rubius_content_datatable")
     */
    public function getContentDataAction()
    {
        /** @var DataTablesInterface $table */
        $table = $this->get('datatable.factory')->getTable('contents');

        return new JsonResponse(
            $table->getData()
        );
    }

    /**
     * @Route(path="/create", name="rubius_content_create")
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function createAction(Request $request)
    {
        $form = $this->createForm('content');

        $form->handleRequest($request);

        if ($form->isValid() && $form->isSubmitted()) {
            /** @var Content $content */
            $content = $form->getData();
            $this->get('doctrine.orm.default_entity_manager')->persist($content);
            $this->get('doctrine.orm.default_entity_manager')->flush();

            return $this->redirect($this->generateUrl('rubius_content_index'));
        }

        return $this->render(
            '@RubiusAdmin/CMS/content/create.html.twig',
            [
                'form' => $form->createView()
            ]
        );


    }

    /**
     * @Route(path="/{id}/edit", name="rubius_content_edit")
     * @param Request $request
     * @param Content $content
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|\Symfony\Component\HttpFoundation\Response
     */
    public function editAction(Request $request, Content $content)
    {
        $form = $this->createForm('content', $content);
        $form->handleRequest($request);

        if ($form->isValid() && $form->isSubmitted()) {
            $content->uploadPrePersist();
            $this->get('doctrine.orm.default_entity_manager')->flush($content);

            return $this->redirect($this->generateUrl('rubius_content_index'));
        }
        return $this->render(
            '@RubiusAdmin/CMS/content/create.html.twig',
            [
                'form' => $form->createView(),
                'content' => $content
            ]
        );
    }

    /**
     * @Route(path="/{id}/delete", name="rubius_content_delete")
     */
    public function deleteAction()
    {

    }
}

src/Rubius/AdminBundle/Controller/CMS/ContentTypeController.php
<?php
/**
 * @Author: Rúdi Rocha <rudi.rocha@gmail.com>
 */

namespace Rubius\AdminBundle\Controller\CMS;


use Rubius\AdminBundle\Controller\DefaultController;
use Rubius\AdminBundle\Entity\ContentType;
use Rubius\DataTablesBundle\Library\DataTablesInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Class ContentTypeController
 * @package Rubius\AdminBundle\Controller\CMS
 * @Security("has_role('ROLE_USER')")
 */
class ContentTypeController extends DefaultController
{
    /**
     * @Route(path="/", name="rubius_content_type_index")
     * @return Response
     */
    public function indexAction()
    {
        /** @var DataTablesInterface $table */
        $table = $this->get('datatable.factory')->getTable('contentTypes');

        return $this->render(
            'RubiusAdminBundle:CMS/content-type:index.html.twig',
            [
                'table' => $table->getDataTableObject($this->generateUrl('rubius_content_types_datatable'))
            ]
        );

    }

    /**
     * @Route(path="/getContentTypesData", name="rubius_content_types_datatable")
     */
    public function getContentTypesDataAction()
    {
        /** @var DataTablesInterface $table */
        $table = $this->get('datatable.factory')->getTable('contentTypes');

        return new JsonResponse(
            $table->getData()
        );
    }

    /**
     * @Route(path="/create", name="rubius_content_type_create")
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|Response
     */
    public function createAction(Request $request)
    {
        $form = $this->createForm('content_type');

        $form->handleRequest($request);
        if ($form->isValid() && $form->isSubmitted())
        {
            /** @var ContentType $contentType */
            $contentType = $form->getData();
            $this->get('doctrine.orm.default_entity_manager')->persist($contentType);
            $this->get('doctrine.orm.default_entity_manager')->flush();

            return $this->redirect($this->generateUrl('rubius_content_type_index'));
        }
        return $this->render(
            '@RubiusAdmin/CMS/content-type/create.html.twig',
            [
                'form' => $form->createView()
            ]
        );
    }

    /**
     * @Route(path="/{id}/edit", name="rubius_content_type_edit")
     * @param Request $request
     * @param ContentType $contentType
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|Response
     */
    public function editAction(Request $request, ContentType $contentType)
    {
        $form = $this->createForm('content_type', $contentType);

        $form->handleRequest($request);
        if ($form->isValid() && $form->isSubmitted())
        {
            /** @var ContentType $contentType */
            $contentType = $form->getData();
            $contentType->uploadPrePersist();
            $this->get('doctrine.orm.default_entity_manager')->flush();

            return $this->redirect($this->generateUrl('rubius_content_type_index'));
        }
        return $this->render(
            '@RubiusAdmin/CMS/content-type/create.html.twig',
            [
                'form' => $form->createView(),
                'contentType' => $contentType
            ]
        );
    }

    /**
     * @Route(path="/{id}/delete", name="rubius_content_type_delete")
     * @param ContentType $contentType
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     */
    public function deleteContentTypeAction(ContentType $contentType)
    {
        $this->get('doctrine.orm.default_entity_manager')->remove($contentType);
        $this->get('doctrine.orm.default_entity_manager')->flush();
        return $this->redirect($this->generateUrl('rubius_content_type_index'));
    }

}

src/Rubius/AdminBundle/Resources/views/CMS/content/create.html.twig
{% trans_default_domain 'rubiusAdmin' %}
{% extends 'RubiusAdminBundle:layout:main.html.twig' %}
{% block breadcrumbs %}
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">{{ 'rubiusAdmin.cms.content.title' | trans }}</li>
    </ol>
{% endblock %}

{% block pageTitle %}
    {{ 'rubiusAdmin.cms.content.title' | trans }}
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-lg-12">
            <div class="box">
                <div class="box-header with-border">
                    <h3 class="box-title">
                        {% if contentType is not defined %}
                            {{ 'rubiusAdmin.cms.content.create.title' | trans }}
                        {% else %}
                            {{ 'rubiusAdmin.general.Edit' |trans }} {{ contentType.title }}
                        {% endif %}
                    </h3>
                    <div class="box-tools pull-right">
                        <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                    </div>
                </div>
                <div class="box-body">
                    {{ form_start(form) }}
                    <div class="row margin-bottom">
                        <div class="col-lg-6">
                            {{ form_row(form.title) }}
                        </div>
                        <div class="col-lg-6">
                            {{ form_row(form.alias) }}
                        </div>
                    </div>
                    <div class="row margin-bottom">
                        <div class="col-lg-3">
                            {{ form_label(form.publishedDate) }}
                            <div class="input-group">
                                <div class="input-group-addon">
                                    <i class="fa fa-calendar"></i>
                                </div>
                                {{ form_widget(form.publishedDate) }}
                            </div>

                        </div>
                        <div class="col-lg-3">
                            <div class="col-lg-12">{{ form_label(form.active) }}</div>
                            <div class="col-lg-12">{{ form_widget(form.active) }}</div>
                        </div>
                        <div class="col-lg-6">
                            {{ form_label(form.forwardUrl) }}
                            {{ form_widget(form.forwardUrl) }}
                        </div>
                    </div>
                    <div class="nav-tabs-custom">
                        <ul class="nav nav-tabs">
                            <li class="active"><a href="#tab_content" data-toggle="tab">{{ 'rubiusAdmin.cms.content.create.tabContent' | trans }}</a></li>
                            <li><a href="#tab_images" data-toggle="tab">{{ 'rubiusAdmin.cms.content.create.tabImages' | trans }}</a></li>
                            <li><a href="#tab_meta" data-toggle="tab">{{ 'rubiusAdmin.cms.content.create.tabMeta' | trans }}</a></li>

                        </ul>
                        <div class="tab-content">
                            <div class="tab-pane active" id="tab_content">
                                <div class="row margin-bottom">
                                    <div class="col-lg-12">
                                        {{ form_label(form.contentType) }}
                                    </div>
                                    <div class="col-lg-12">
                                        {{ form_widget(form.contentType) }}
                                    </div>
                                </div>
                                <div class="row margin-bottom">
                                    <div class="col-lg-12">{{ form_label(form.intro) }}</div>
                                    <div class="col-lg-12">{{ form_widget(form.intro) }}</div>
                                </div>
                                <div class="row margin-bottom">
                                    <div class="col-lg-12">
                                        {{ form_label(form.body) }}
                                    </div>
                                    <div class="col-lg-12">
                                        {{ form_widget(form.body) }}
                                    </div>
                                </div>
                            </div>
                            <div class="tab-pane" id="tab_images">
                                <div class="row">
                                    <div class="col-lg-6">{{ form_row(form.smallImageObject) }}</div>
                                    <div class="col-lg-6">
                                        {% if content is defined and content.smallImage is not empty %}
                                            <img src="{{ asset(content.smallImageUrl) }}" width="150px"/>
                                        {% endif %}
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-lg-6">{{ form_row(form.mediumImageObject) }}</div>
                                    <div class="col-lg-6">
                                        {% if content is defined and content.mediumImage is not empty %}
                                            <img src="{{ asset(content.mediumImageUrl) }}" width="150px"/>
                                        {% endif %}
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-lg-6">{{ form_row(form.bigImageObject) }}</div>
                                    <div class="col-lg-6">
                                        {% if content is defined and content.bigImage is not empty %}
                                            <img src="{{ asset(content.bigImageUrl) }}" width="150px"/>
                                        {% endif %}
                                    </div>
                                </div>

                            </div>
                            <div class="tab-pane" id="tab_meta">
                                {{ form_row(form.metaTags) }}
                                {{ form_row(form.metaDescription) }}
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-6">
                            <input type="submit" class="btn btn-success" value="{{ 'rubiusAdmin.general.submit' | trans }}"/>
                        </div>
                    </div>
                    {{ form_end(form)}}
                </div>
            </div>
        </div>

    </div>
{% endblock %}

{% block styles %}
    <link rel="stylesheet" href="{{ asset('assets/bootstrap-datepicker/bootstrap-datepicker.css') }}">
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script src="{{ asset('assets/ckeditor/ckeditor.js') }}"></script>
    <script src="{{ asset('assets/bootstrap-datepicker/bootstrap-datepicker.js') }}"></script>
    <script>
        $(document).ready(function(){
            $(".datepicker").datepicker({
                format: "dd/mm/yyyy",
                todayBtn: "linked",
                language: "{{ app.request.getLocale() }}",
                todayHighlight: true
            });
        });
        $(function () {
            CKEDITOR.replace('ckeditor' );
        });
    </script>
{% endblock %}

src/Rubius/AdminBundle/Resources/views/CMS/content/index.html.twig
{% trans_default_domain 'rubiusAdmin' %}
{% extends 'RubiusAdminBundle:layout:main.html.twig' %}
{% block breadcrumbs %}
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">{{ 'rubiusAdmin.cms.content.title' | trans }}</li>
    </ol>
{% endblock %}

{% block pageTitle %}
    {{ 'rubiusAdmin.cms.content.title' | trans }}
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-lg-12">
            <div class="box">
                <div class="box-header with-border">
                    <h3 class="box-title">{{ 'rubiusAdmin.cms.content.index.titleOptions' | trans }}</h3>
                    <div class="box-tools pull-right">
                        <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                    </div>
                </div>
                <div class="box-body">
                    <div class="row no-margin">
                        <div class="col-lg-1">
                            <a class="btn btn-success" href="{{ path('rubius_content_create') }}">
                                <i class="fa fa-plus"></i> {{ 'rubiusAdmin.general.new' | trans }}
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="box">
                <div class="box-body">
                    <div class="row">
                        <div class="col-lg-12">
                            <table id="data-table"></table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block styles %}
    {{ parent() }}
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.9/css/jquery.dataTables.min.css"/>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script src="https://cdn.datatables.net/1.10.9/js/jquery.dataTables.min.js"></script>
    <script>
        $(document).ready(function(){
            $('#data-table').DataTable( {{ table | raw }} );
            $(".btn-delete").click(function(e){
                if (!confirm("Are you sure?")) {
                    e.preventDefault();
                }
            });
            $("#rubius-left-cms").addClass("active");
            $("#rubius-left-cms-content").addClass("active");
        });


    </script>

{% endblock %}